//FUCK YOU, FUCK YOU ALL... I HATE EVERY SINGLE ON OF YOU BASTARDS, YOU MADE ME DO THIS. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
/*
/obj/item/bodypillow
	name = "Anime Body Pillow"

THIS WILL BE CODED MUCH MUCH LATER
*/
