#undef SS13LIB_HTTP_GET
#undef SS13LIB_HTTP_POST

#undef SS13LIB_INFO_LOG
#undef SS13LIB_WARNING_LOG
#undef SS13LIB_ERROR_LOG

#undef SS13LIB_QUERY_CODE
#undef SS13LIB_PREFLIGHT_CODE

#undef SS13LIB_HUB_SERVER
#undef SS13LIB_CKEY_SUFFIX
