Admin:
  - 'code/modules/admin/**'
  - 'waspstation/code/modules/admin/**'

# Any file within the config subfolder
Config:
  - 'config/**'

Dependencies:
  - '**/package.json'
  - '**/package-lock.json'
  - '**/yarn.lock'

# When the .DME is changed
DME Edit:
  - './*.dme'
  - '**/*.dme'

# Any .dmi changes
Sprites:
  - '**/*.dmi'

# Changes to a .dmm or anything in the _map subfolder
Map Change:
  - '**/*.dmm'
  - '_maps/**'

# Any changes to .ogg files are marked as sound
Sound:
  - '**/*.ogg'

# Changes to the SQL subfolder
SQL:
  - 'SQL/**'

# Changes to the tgui subfolder
tgui:
  - 'tgui/**'

# Changes to the .Github subfolder
Github:
  - '.github/**'
