// Config, comments shits out to disable features

#define ANGLEGRINDER_OUTPOST_PRICE 1000
// #define ANGLEGRINDER_BROKEN_MACHINE_SALVAGE_TIME 2.5 SECONDS
#define ANGLEGRINDER_OPEN_SAFE_TIME 90 SECONDS
#define ANGLEGRINDER_OPEN_CLOSET_TIME 5 SECONDS
#define ANGLEGRINDER_RAILING_TIME 1 SECONDS
#define ANGLEGRINDER_MACHINE_FRAME_TIME 3 SECONDS
