#define CREDIT_LOG_WITHDRAW "cash"
#define CREDIT_LOG_TRANSFER_IN "transfer"
#define CREDIT_LOG_TRANSFER_OUT "transfer_out"
#define CREDIT_LOG_DEPOSIT "deposit"
#define CREDIT_LOG_STARTING_MONEY "starting_money"
#define CREDIT_LOG_VENDOR_PURCHASE "vendor_purchase"
#define CREDIT_LOG_MISSION "mission"
#define CREDIT_LOG_CARGO "cargo_purchase"
#define CREDIT_LOG_BOUNTY "bounty"
#define CREDIT_LOG_SYNDICATE_CONTRACT "syndicate_contract"
#define CREDIT_LOG_SELLING_PAD "selling_pad"

