#define RUINTYPE_LAVA "Lava"
#define RUINTYPE_SAND "Sand"
#define RUINTYPE_JUNGLE "Jungle"
#define RUINTYPE_ICE "Ice"
#define RUINTYPE_SPACE "Space"
#define RUINTYPE_ROCK "Rock"
#define RUINTYPE_YELLOW "Yellow"

#define RUINTYPE_LIST_ALL list(RUINTYPE_LAVA, RUINTYPE_SAND, RUINTYPE_JUNGLE, RUINTYPE_ICE, RUINTYPE_SPACE, RUINTYPE_ROCK, RUINTYPE_YELLOW)
