#define SHIPBOT_TOPIC var/shipbot_return = SSshipbot.do_topic(args[1]); if(shipbot_return) return shipbot_return

#define SHIPBOT_TOPIC_PING "PING"

/// CLIENT, MESSAGE
#define SHIPBOT_TOPIC_RELAY_OOC "RELAY_OOC"

/// CLIENT, MESSAGE
#define SHIPBOT_TOPIC_RELAY_ADMIN_SAY "RELAY_ADMIN_SAY"

/// CLIENT, MESSAGE, TARGET
#define SHIPBOT_TOPIC_RELAY_ADMIN_PM "RELAY_ADMIN_HELP"

/// CLIENT, MESSAGE
#define SHIPBOT_TOPIC_RELAY_MENTOR_SAY "RELAY_MENTOR_SAY"

/// CLIENT, MESSAGE, TARGET
#define SHIPBOT_TOPIC_RELAY_MENTOR_PM "RELAY_MENTOR_PM"

#define SHIPBOT_TOPIC_RELAY_CHANNEL_LIST "RELAY_CHANNEL_LIST"

#define SHIPBOT_TOPIC_RESPONSE_GOOD "RESPONSE_GOOD"
#define SHIPBOT_TOPIC_RESPONSE_FAIL "RESPONSE_FAIL"
#define SHIPBOT_TOPIC_RESPONSE_BAD_COMMAND "RESPONSE_BAD_COMMAND"
