#define DIGITIGRADE_PATH 'icons/mob/species/misc/digitigrade.dmi'
#define DIGITIGRADE_SHOES_PATH 'icons/mob/species/misc/digitigrade_shoes.dmi'
#define DIGITIGRADE_ACCESSORY_PATH 'icons/mob/species/misc/digitigrade_accessory.dmi'
#define DIGITIGRADE_SUIT_PATH 'icons/mob/species/misc/digitigrade_suits.dmi'

///HUMAN PATHS
#define DEFAULT_UNIFORM_PATH 'icons/mob/uniform.dmi'
#define DEFAULT_BACK_PATH 'icons/mob/clothing/back.dmi'
#define DEFAULT_SHOES_PATH 'icons/mob/clothing/feet.dmi'
#define DEFAULT_SUIT_PATH 'icons/mob/clothing/suit.dmi'
#define DEFAULT_EARS_PATH 'icons/mob/clothing/ears.dmi'
#define DEFAULT_MASK_PATH 'icons/mob/clothing/mask.dmi'
#define DEFAULT_HEAD_PATH 'icons/mob/clothing/head.dmi'
#define DEFAULT_NECK_PATH 'icons/mob/clothing/neck.dmi'
#define DEFAULT_GLOVES_PATH 'icons/mob/clothing/hands.dmi'
#define DEFAULT_GLASSES_PATH 'icons/mob/clothing/eyes/eyes.dmi'
#define DEFAULT_BELT_PATH 'icons/mob/clothing/belt.dmi'

///VOX PATHS
#define VOX_UNIFORM_PATH 'icons/mob/species/vox/onmob_uniform_vox.dmi'
#define VOX_BACK_PATH 'icons/mob/species/vox/onmob_back_vox.dmi'
#define VOX_SHOES_PATH 'icons/mob/species/vox/onmob_feet_vox.dmi'
#define VOX_ACCESSORY_PATH 'icons/mob/species/vox/onmob_accessory_vox.dmi'
#define VOX_SUIT_PATH 'icons/mob/species/vox/onmob_suit_vox.dmi'
#define VOX_EARS_PATH 'icons/mob/species/vox/onmob_ears_vox.dmi'
#define VOX_MASK_PATH 'icons/mob/species/vox/onmob_mask_vox.dmi'
#define VOX_NECK_PATH 'icons/mob/species/vox/onmob_neck_vox.dmi'
#define VOX_HEAD_PATH 'icons/mob/species/vox/onmob_head_vox.dmi'
#define VOX_GLOVES_PATH 'icons/mob/species/vox/onmob_hands_vox.dmi'
#define VOX_GLASSES_PATH 'icons/mob/species/vox/onmob_eyes_vox.dmi'
#define VOX_BELT_PATH 'icons/mob/species/vox/onmob_belt_vox.dmi'
#define VOX_UNDERWEAR_TORSO_PATH 'icons/mob/clothing/underwear/species/vox/underwear_torso_vox.dmi'
#define VOX_UNDERWEAR_LEGS_PATH 'icons/mob/clothing/underwear/species/vox/underwear_legs_vox.dmi'
#define VOX_UNDERWEAR_SOCKS_PATH 'icons/mob/clothing/underwear/species/vox/underwear_socks_vox.dmi'

///KEPORI PATHS
#define KEPORI_UNIFORM_PATH 'icons/mob/species/kepori/onmob_uniform_kepori.dmi'
#define KEPORI_BACK_PATH 'icons/mob/species/kepori/onmob_back_kepori.dmi'
#define KEPORI_SHOES_PATH 'icons/mob/species/kepori/onmob_feet_kepori.dmi'
#define KEPORI_ACCESSORY_PATH 'icons/mob/species/kepori/onmob_accessory_kepori.dmi'
#define KEPORI_SUIT_PATH 'icons/mob/species/kepori/onmob_suit_kepori.dmi'
#define KEPORI_EARS_PATH 'icons/mob/species/kepori/onmob_ears_kepori.dmi'
#define KEPORI_MASK_PATH 'icons/mob/species/kepori/onmob_mask_kepori.dmi'
#define KEPORI_HEAD_PATH 'icons/mob/species/kepori/onmob_head_kepori.dmi'
#define KEPORI_NECK_PATH 'icons/mob/species/kepori/onmob_neck_kepori.dmi'
#define KEPORI_GLASSES_PATH 'icons/mob/species/kepori/onmob_eyes_kepori.dmi'
#define KEPORI_GLOVES_PATH 'icons/mob/species/kepori/onmob_hands_kepori.dmi'
#define KEPORI_BELT_PATH 'icons/mob/species/kepori/onmob_belt_kepori.dmi'
#define KEPORI_UNDERWEAR_TORSO_PATH 'icons/mob/clothing/underwear/species/kepori/underwear_torso_kepori.dmi'
#define KEPORI_UNDERWEAR_LEGS_PATH 'icons/mob/clothing/underwear/species/kepori/underwear_legs_kepori.dmi'
#define KEPORI_UNDERWEAR_SOCKS_PATH 'icons/mob/clothing/underwear/species/kepori/underwear_socks_kepori.dmi'
