/datum/outfit/generic/pre_equip(mob/living/carbon/human/H, visualsOnly = FALSE)
	. = ..()
	uniform = pickweight(list(
		/obj/item/clothing/under/utility = 1,
		/obj/item/clothing/under/utility/skirt = 1,
		/obj/item/clothing/under/color/black = 1,
		/obj/item/clothing/under/color/white = 1,
		/obj/item/clothing/under/color/random = 1,
		/obj/item/clothing/under/shorts/black = 1,
		/obj/item/clothing/under/shorts/grey = 1,
		/obj/item/clothing/under/shorts/blue = 1,
		/obj/item/clothing/under/shorts/green = 1,
		/obj/item/clothing/under/pants/jeans = 1,
		/obj/item/clothing/under/pants/khaki = 1,
		/obj/item/clothing/under/pants/tan = 1,
		/obj/item/clothing/under/pants/white = 1,
		/obj/item/clothing/under/pants/red = 1,
		/obj/item/clothing/under/pants/track = 1,
		/obj/item/clothing/under/pants/blackjeans = 1,
		/obj/item/clothing/under/pants/black = 1,
		/obj/item/clothing/under/pants/camo = 1,
		/obj/item/clothing/under/suit/sl = 1,
		/obj/item/clothing/under/suit/white = 1,
		/obj/item/clothing/under/suit/tan = 1,
		/obj/item/clothing/under/suit/black_really = 1,
		/obj/item/clothing/under/suit/black_really/skirt = 1,
		/obj/item/clothing/under/suit/navy = 1,
		/obj/item/clothing/under/suit/burgundy = 1,
		/obj/item/clothing/under/suit/charcoal = 1,
		/obj/item/clothing/under/rank/civilian/lawyer/galaxy = 1,
		/obj/item/clothing/under/suit/black/skirt = 1,
		/obj/item/clothing/under/rank/command/captain/suit/skirt = 1,
		/obj/item/clothing/under/rank/command/head_of_personnel/suit/skirt = 1,
		/obj/item/clothing/under/suit/black = 1,
		/obj/item/clothing/under/suit/checkered = 1,
		/obj/item/clothing/under/dress/sailor = 1,
		/obj/item/clothing/under/dress/striped = 1,
		/obj/item/clothing/under/dress/skirt/purple = 1,
		/obj/item/clothing/under/dress/skirt/blue = 1,
		/obj/item/clothing/under/dress/skirt/red = 1,
		/obj/item/clothing/under/dress/skirt = 1,
		/obj/item/clothing/under/dress/sundress = 1,
		/obj/item/clothing/under/suit/dresssuit = 1,
		/obj/item/clothing/under/suit/dresssuit/skirt = 1,
		/obj/item/clothing/under/syndicate/tacticool = 1,
		/obj/item/clothing/under/costume/maid = 1
		)
	)

/datum/outfit/generic
	name "Generic"
