/datum/unit_test/spawn_gun/Run()
	for(var/gun_to_test in subtypesof(/obj/item/gun))
		var/obj/item/gun/gun = allocate(gun_to_test, TRUE)
		if(gun.default_ammo_type && !(gun.default_ammo_type in gun.allowed_ammo_types))
			TEST_FAIL("[gun] has a specified default_ammo_type [gun.default_ammo_type] that is not present in the allowed_ammo_types.")
